### ISSUE TITLE
On the main Incidents page, for Recent Incidents, display the street name between the city and incident number

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#208] opened 2019-09-25 16:11 UTC

**Comment by kfogel** [comment] 2019-09-25 18:56
The problem we're solving here is that you get eight incidents in a row showing just "Chicago", "Chicago", "Chicago", etc, with nothing else to distinguish them except their incident numbers.  Showing the street name will give a human enough to immediately distinguish one incident from another in a listing of multiple incidents.

**Comment by frankduncan** [comment] 2020-06-19 13:07
This is actually a duplicate of #143, so going to do the work over there.

**Closed by frankduncan** 2020-06-19 13:07 UTC
Labels: XS, high-priority, incidents
