### ISSUE TITLE
When querying data from the More Incidents... page, Clicking 'Search' after selecting 'Show statistics' and 'Closed' produces an application error (and blank page)

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#150] opened 2018-02-05 23:41 UTC
When querying data from the More Incidents... page, Clicking **Search** after selecting **Show statistics** and **Closed** produces an application error (and a blank page). Selecting **Open** or **Invalid** produce the normal result.

<img width="1280" alt="more incidents" src="https://user-images.githubusercontent.com/4147733/35834475-97ad544a-0a9b-11e8-932b-ad29327df204.png">

**Comment by bnazari** [comment] 2018-02-05 23:48
It seems that the problem isn’t so much with the category, as it is the number of entries. I was able to get the 500 error with Open as well as Closed incidents when I went back to July, but when I changed it to January 2018, the problem went away. My gut says it has to do with the mapping part of the system, but I will investigate more and report back. Good catch on this one!

**Comment by OhMcGoo** [comment] 2018-02-06 00:03
Unlike LA, we close all our incident reports . . .

. . . Ooh!

On Feb 5, 2018, at 5:48 PM, bnazari <notifications@github.com<mailto:notifications@github.com>> wrote:

It seems that the problem isn’t so much with the category, as it is the number of entries. I was able to get the 500 error with Open as well as Closed incidents when I went back to July, but when I changed it to January 2018, the problem went away. My gut says it has to do with the mapping part of the system, but I will investigate more and report back. Good catch on this one!

**Comment by bnazari** [comment] 2018-02-06 00:24
Ooooh, that one hurt a bit! 

Okay, got some news regarding this one. I looked at PaperTrail and saw the query it is trying to run:

SELECT extract(epoch from (SELECT  "incidents_event_logs"."event_time" FROM "incidents_event_logs"  WHERE (("incidents_event_logs"."event" IN ('dat_on_scene') AND "incidents_event_logs"."incident_id" = "incidents_incidents"."id"))  ORDER BY "incidents_event_logs"."event_time" LIMIT 1) - (SELECT  "incidents_event_logs"."event_time" FROM "incidents_event_logs"  WHERE (("incidents_event_logs"."event" IN ('dispatch_received', 'dispatch_note', 'dat_received', 'dispatch_relayed', 'responders_identified') AND "incidents_event_logs"."incident_id" = "incidents_incidents"."id"))  ORDER BY "incidents_event_logs"."event_time" LIMIT 1)) AS duration FROM "incidents_incidents"  WHERE "incidents_incidents"."chapter_id" IN (7) AND "incidents_incidents"."status" != 'invalid' AND (("incidents_incidents"."status" IN ('open', 'closed') AND "incidents_incidents"."date" >= '2017-07-01')) AND (("incidents_incidents"."lat" IS NOT NULL AND "incidents_incidents"."lng" IS NOT NULL AND "incidents_incidents"."lat" != 0 AND "incidents_incidents"."lng" != 0)) 

Well from what I can gather, it fails when the query takes more that 30 seconds to run. (The query from Sept 24th took 29.61 seconds to run) If I went back to the beginning too the fiscal year, that query took the LA region 46 seconds to run. I did the same with Chicago and it took 89 seconds to run. 

In order to fix this, we can either extend the timeout for the query or find a way to speed up the DB. What do you folks think?

Bernie

**Comment by OhMcGoo** [comment] 2018-02-06 00:42
I’ve never had a query take more than 5-10 seconds . . . ever.

**Comment by bnazari** [comment] 2018-02-06 00:53
Well, there is something different happening then. I’m directly hitting the query for the call duration calculation. The webpage times out after 30 seconds, but the query takes a bit longer. Heck I can tell you right now that if you run Chicago’s open and closed incidents, it will time out right around December 8th or so. Around November, you are already looking at 40+ seconds query times. But I can definitely tell you that is where the problem is. Can we had some horsepower to the DB or optimize it?

**Comment by pjsier** [comment] 2018-02-06 14:54
Heroku has a hard request limit of 30 seconds, so there's no getting around that. We can take a look at the indexes on the database, and potentially add some for some of the fields getting queried frequently here to speed things up. If we can't get much performance improvement from that it may be something we try and offload onto Periscope? Depending on where this goes, we can also have longer-running background jobs

**Comment by OhMcGoo** [comment] 2018-02-06 15:13
As I mentioned previously, these queries have never taken longer than 5-10 seconds.

Is this a result of moving from a Premium DB to a Standard DB?

This is not something we can offload to Periscope as this functionality is integral to how many use the app.


Jim McGowan
American Red Cross
312-848-6726 (m)
jim.mcgowan@redcross.org<http://jim.mcgowan@redcross.org>

On Feb 6, 2018, at 8:54 AM, Patrick Sier <notifications@github.com<mailto:notifications@github.com>> wrote:


Heroku has a hard request limit of 30 seconds, so there's no getting around that. We can take a look at the indexes on the database, and potentially add some for some of the fields getting queried frequently here to speed things up. If we can't get much performance improvement from that it may be something we try and offload onto Periscope? Depending on where this goes, we can also have longer-running background jobs

**Comment by pjsier** [comment] 2018-02-06 15:17
Ah I misunderstood, I thought you meant this was happening for specific regions with more records. I can take a closer look

**Comment by OhMcGoo** [comment] 2018-02-06 15:25
Well, now it’s timing it out. It’s never done this until recently.

**Comment by pjsier** [comment] 2018-02-06 16:22
Looking at some of the database diagnostics, this is the longest running query by a long shot. On average it takes about 45-60 seconds. The next slowest query averages about 10-15 seconds, and the one after that is around 2 seconds.

It looks like that individual query is actually just getting the average response time, and when I remove that I can load a statistics search going back a few years without any issue. I'm guessing response time is an important number to have, but one thing we could do is create a response time column on incidents which is updated on a nightly basis for closed incidents or incidents that are more than a day old. That way, instead of doing a complicated query for every single incident, it would just be a straight call to average.

A few questions off of that:
* Should we remove average response time from the results until this is resolved so that it's usable in the meantime?
* Are there any issues with updating response time on a per-incident basis with a day or so delay?

I imagine this became an issue recently because of the database downgrade, but since it's the only query that's causing a problem it seems worth trying to resolve the issue rather than paying more again.

**Comment by bnazari** [comment] 2018-02-06 17:41
Why don’t we have just add a field to the incident table and a cron job that calculates the response time for each incident the following day? That way, the DB will only need to do an average of 500 or so numbers.

**Comment by pjsier** [comment] 2018-02-06 17:44
Right, that's what I'm thinking, sounds good! I can take that

**Comment by bnazari** [comment] 2018-02-06 18:13
Have a dumb question: I ran the query on my local machine and it took .15 seconds. Are the shared servers actually 18,000X slower? Seems like there is something else going on to me.

**Comment by pjsier** [comment] 2018-02-06 18:16
That's odd, when I ran it on mine with a full production backup it took twice as long. Do you have the full data locally?

**Comment by OhMcGoo** [comment] 2018-02-06 18:20
One question:

I can’t always say that our volunteers do the smartest things and sometimes they will record an off scene time that’s actually BEFORE the time they we dispatched the incident. Thus, in theory, responders "left the scene before we asked them to go." Could this negative math be part of the problem?

**Comment by pjsier** [comment] 2018-02-06 18:26
@OhMcGoo that's good to know, but I don't think that would cause the issue since Postgres can handle negative time intervals. The current query is running once per incident returned and then aggregating that, so it looks like it's more based on size.

That said, for any updates here, would you want to ignore negative response times in an average so that they don't skew the results?

**Comment by bnazari** [comment] 2018-02-06 18:36
Now this is interesting. I had initially run the query with the last backup from BLACK (5 days ago) and it took .26 seconds. Decided to grab the backup from last night and import it the same way I did for BLACK and now it takes 113.95 seconds. What would case this? Same exact query, same machine. The only difference is that in the last 5 days, we’ve had 9 additional incidents.

**Comment by pjsier** [comment] 2018-02-06 18:46
@bnazari hmm, that makes me think there was an index in the previous version of the database that wasn't migrated because it was added outside the Rails schema. Do you see any differences in the database structure? I can pull it as well as take a look

**Comment by bnazari** [comment] 2018-02-06 18:54
Didn’t take that close of a look as I’m running off to meetings right now. Just did a PG-restore and ran the query I got from the logs. Definitely sounds like some indexing or vacuuming might be in order. I would run the query with an EXPLAIN and see if there is something glaring at you. The difference is too stark to have something to do with just the smaller DB instance. Specially since Jim was saying the queries only took 5 seconds or so a week ago.

**Comment by pjsier** [comment] 2018-02-06 19:22
Just looked into this using EXPLAIN, and it looks like a lot of the table indexes weren't recreated in the database migration. There must have been an issue with moving the schema over, but fortunately we should be able to fix this by adding those indexes back. @pmacaluso3 any thoughts on the best way of doing this?

**Comment by pjsier** [comment] 2018-02-06 19:49
To confirm that it's an index issue, I just pulled a fresh production backup and added all of the indexes locally, and now the query runs almost immediately. I can make another backup to be safe and then run this later tonight or early tomorrow morning

**Comment by pjsier** [comment] 2018-02-07 03:50
Closed after the index update based on confirmation from @OhMcGoo

**Closed by pjsier** 2018-02-07 03:50 UTC

**Comment by bnazari** [comment] 2018-02-07 04:29
Same queries are running at .21 seconds now. Great job with the fix, folks!!
