### ISSUE TITLE
Update Regional boundary maps on Region's Incidents pages

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/arcdata#36] opened 2016-01-09 17:48 UTC
On the Incidents pages, update Regional boundary maps to reflect new Regional geographies. These North Central Division Regions have incorrect boundary maps:

**Idaho-Montana**
<img width="748" alt="idaho-montana" src="https://cloud.githubusercontent.com/assets/4147733/12217411/22b2575c-b6c5-11e5-9f0b-8c1a33719119.png">

**Kansas-Nebraska**
<img width="750" alt="kansas-nebraska" src="https://cloud.githubusercontent.com/assets/4147733/12217412/2dab9dbc-b6c5-11e5-8f9e-e087d8aa7397.png">

**Minnesota**
<img width="747" alt="minnesota" src="https://cloud.githubusercontent.com/assets/4147733/12217414/37c44272-b6c5-11e5-8ffc-e0b6946c7cf2.png">

**Chicago & Northern Illinois**
<img width="749" alt="chicago northern illinois" src="https://cloud.githubusercontent.com/assets/4147733/12217416/41b78a0a-b6c5-11e5-9266-822c0f4af5d7.png">

**Central & Southern Illinois**
<img width="749" alt="central southern illinois" src="https://cloud.githubusercontent.com/assets/4147733/12217417/4d85de7c-b6c5-11e5-9d01-9aa62030b718.png">

**Comment by jasonwinget** [comment] 2016-01-23 17:25
I have updated the boundaries in a Fusion table as requested by @OhMcGoo

**Comment by OhMcGoo** [comment] 2016-01-26 01:49
@jlaxson: Here are the links to the Regional/Chapter boundaries Fusion Table: 

https://www.google.com/fusiontables/embedviz?viz=GVIZ&t=TABLE&q=select+col3%2C+col1%2C+col2+from+1mqUHwLANNDmN4313nYMYN9x1esviXSdlKPQnKQzF&containerId=googft-gviz-canvas

https://www.google.com/fusiontables/embedviz?q=select+col2+from+1mqUHwLANNDmN4313nYMYN9x1esviXSdlKPQnKQzF&viz=MAP&h=false&lat=39.21918141003138&lng=-105.45508456835938&t=1&z=5&l=col2&y=2&tmplt=2&hml=KML

**Comment by OhMcGoo** [comment] 2016-01-26 02:54
@jlaxson: Here are the links to the Regional/Chapter boundaries Fusion Table:

Rows:
https://www.google.com/fusiontables/embedviz?viz=GVIZ&t=TABLE&q=select+col0%2C+col1%2C+col2+from+19-2xEahVmhKmQ8O0zNmceFZ8mSf7gvUD_Bk-hkuV&containerId=googft-gviz-canvas

Map:
https://www.google.com/fusiontables/embedviz?q=select+col2+from+19-2xEahVmhKmQ8O0zNmceFZ8mSf7gvUD_Bk-hkuV&viz=MAP&h=false&lat=39.901116951906985&lng=-100.68661162500007&t=1&z=5&l=col2&y=2&tmplt=2&hml=KML

The Fusion Table lives in the NorCen Admin SitCell account.

**Comment by Norman-Lee** [comment] 2016-08-22 00:15
@OhMcGoo @jlaxson Hey guys, I've been meaning to contribute to this repo ever since it popped up at Hack Illinois as one of the open source projects that the students could work on. (I was a recent graduate so one of those emails got shot over my way). 

As for this issue (I started working on it), is there anything that I would have to do other than make sure that I've changed the coffee script from using UNIT_CODE to using the name from the fusion table. Or is there extra configuration that I have to do to get it to read the fusion table besides creating an environment variable for the table id.

**Comment by cecilia-donnelly** [comment] 2017-12-11 22:59
Hey @OhMcGoo, is this still an ongoing problem?  (cc: @bnazari)

**Comment by kfogel** [comment] 2017-12-14 06:39
@cecilia-donnelly, I think I can answer that: I believe it is still an open issue.

The thing is, we _have_ the updated boundary files -- they just need to be deployed.  So this should be a relatively easy fix (famous last words).  We have access to the updated data in the Fusion tables; I just checked the links from @OhMcGoo's earlier comment and they still work.

@OhMcGoo gave me a good reproduction recipe.  It uses a personal name that I don't want to put in a public issue, so I'll sketch the recipe below and send you and the developers the name by other means:

Go to Incidents -> (Personal Name) -> Impersonate -> see how the region boundaries are wrong on the map.

**Comment by kfogel** [comment] 2017-12-16 19:25
By the way, we should also create a role account in Fusion Tables, so that DCSOps isn't dependent on continued access being provided by the NorCen Sitcell account.

In the meantime, I've saved a local copy of the data in commit 1b97310.  (I'm not sure that the `doc/` directory is a good long-term home for this, but I didn't see a more appropriate place and didn't want to make a larger-scale decision right then -- please feel free to move it somewhere else in the tree.)

**Comment by bnazari** [comment] 2018-01-03 22:57
There is a Config Variable inside Heroku that has the Fusion table ID in it. I would suspect that by changing the Table ID to the new one, the problem should be solved, given if the tables are configured the same. Should I go ahead and change int?

**Comment by bnazari** [comment] 2018-01-03 23:23
@kfogel The new Fusion tables headers do not match the old Fusion table headers. DCSOps is looking for the headers of "geometry" and "UNIT_CODE". The new one has "geometry" and "name". We can either modify DCSOps or the Fusion table, if we have access to it. In order to modify DCSOps, we change line 135 in "https://github.com/redcross/arcdata/blob/master/app/assets/javascripts/incidents/incidents.js.coffee" from:
      where: "UNIT_CODE='#{filter}'"
to:
      where: "name='#{filter}'"

New fusion table :
https://fusiontables.googleusercontent.com/embedviz?viz=GVIZ&t=TABLE&q=select%20*%20from+19-2xEahVmhKmQ8O0zNmceFZ8mSf7gvUD_Bk-hkuV&containerId=googft-gviz-canvas

Old fusion table:
https://fusiontables.googleusercontent.com/embedviz?viz=GVIZ&t=TABLE&q=SELECT%20*%20FROM%201YP0eSv4nabbUIH12udRcaZM9kKax5mssQ--Axx5A&containerId=googft-gviz-canvas

**Comment by OhMcGoo** [comment] 2018-01-03 23:33
Let me find the Fusion Table. We can then move it to a role account and modify the headers accordingly.

**Comment by bnazari** [comment] 2018-01-03 23:50
That would definitely be the easier change to make for sure, especially because it will be seamless on the DCSOps side of things. Either way, we are ready to close this issue in one of two ways. Both can be done fairly quickly. I'm not changing the Table ID field in DCSOps for now as it will definitely cause and error.

**Comment by OhMcGoo** [comment] 2018-01-04 16:56
I found the boundary Fusion Table. It lives in a Google SitCell account with a username of norcen.admin@sitcell.org. I can provide the password separately. In the meantime, here's a link to the table: https://www.google.com/fusiontables/DataSource?docid=19-2xEahVmhKmQ8O0zNmceFZ8mSf7gvUD_Bk-hkuV. I'm e-mailing a CSV of the data to the group as GitHub doesn't support that file type for upload.

**Comment by OhMcGoo** [comment] 2018-01-05 17:27
Boundaries are not appearing on the main Incidents page for half of the DCSOps-using Regions:
- Gold Country (Sacramento)
- San Diego
- Idaho-Montana
- Kansas-Nebraska
- Minnesota
- Greater New York

**Comment by pjsier** [comment] 2018-01-09 20:12
Most of these are updated, but Kansas-Nebraska doesn't seem to have a current value for the boundary ID in the database. @OhMcGoo is looking into adding a value and/or checking whether the current value for boundary ID is correct

**Comment by kfogel** [comment] 2018-01-10 22:20
Thanks, @pjsier. @OhMcGoo, let us know when you've done everything you planned to do for this.

**Comment by OhMcGoo** [comment] 2018-01-12 20:11
I've reviewed the settings in DCSOps for the Kansas-Nebraska Region and everything seems to be in order. Not sure where to go from here.

**Comment by pjsier** [comment] 2018-01-18 14:33
@OhMcGoo what's the boundary ID listed for Kansas-Nebraska in DCSOps currently? It may be different than the fusion table

**Comment by OhMcGoo** [comment] 2018-01-18 15:47
@pjsier: I fixed it! There was a boundary polygon filter missing (27R12) from the Kansas-Nebraska Scope (Admin > Incidents > Scopes). This issue can now be closed.

**Comment by OhMcGoo** [comment] 2020-07-14 23:23
@frankduncan: Here is the link to a Google Map of the **Illinois Region** boundary:

https://www.google.com/maps/d/drive?state=%7B%22ids%22%3A%5B%221_WuqvQ1AmTCnZvPQqPf7WMrvNkgPt2p9%22%5D%2C%22action%22%3A%22open%22%2C%22userId%22%3A%22101666302266522240491%22%7D&usp=sharing

In addition, I will post a KMZ file of the same boundary.

If drawing a boundary using either the web map or the file is successful, we can have the other 9 boundaries ready to go in half a day.

**Comment by OhMcGoo** [comment] 2020-07-14 23:24
@frankduncan: For some reason, I can't attach a .kmz to an issue. Will send to you by e-mail.

**Comment by OhMcGoo** [comment] 2020-08-09 18:19
@frankduncan 

Map URLs:

**California Gold Country**: https://www.google.com/maps/d/edit?mid=1IMWdVvNN6H6e9Eee-GTjkvdQuuKI9geQ&usp=sharing
**Cascades**: https://www.google.com/maps/d/edit?mid=1n3MvDwMtji87iLSHadLdcn_iSeGbQcX3&usp=sharing
**Greater New York**: https://www.google.com/maps/d/edit?mid=1_K5-RQ4uJyaMLQvKqzO-takksG9sB-im&usp=sharing
**Idaho and Montana**: https://www.google.com/maps/d/edit?mid=1J5DrQuhw83Pcbi_M9-sm8sQWtw5loSc8&usp=sharing
**Illinois**: https://www.google.com/maps/d/edit?mid=1_WuqvQ1AmTCnZvPQqPf7WMrvNkgPt2p9&usp=sharing
**Kansas** (and Oklahoma): https://www.google.com/maps/d/edit?mid=1lJkoc3s1xmyPBQshOPOHOsdVQdl0UHQB&usp=sharing
**Minnesota and Dakotas**: https://www.google.com/maps/d/edit?mid=1MnU3Q8vqSDdxmHfYpeRAkIvxGXjZkCPN&usp=sharing
**Nebraska** (and Iowa): https://www.google.com/maps/d/edit?mid=1DfkchRHH9A8AxLlrmGW_vyN4i-n-COho&usp=sharing
**New Jersey**: https://www.google.com/maps/d/edit?mid=1sQp--rF_A8VJ8IvaRcW87Q9Dv_-5w4OO&usp=sharing
**Northern California Coastal**: https://www.google.com/maps/d/edit?mid=1Jpj7av12LCWUYvDt2Wr-1IZmq38YtuNI&usp=sharing

**Comment by OhMcGoo** [comment] 2020-08-09 18:24
@frankduncan  In addition, all maps have been shared with you directly.

**Comment by frankduncan** [comment] 2020-08-09 18:24
@OhMcGoo I'm going to download the KMZ for all of these boundaries and put them in the repository.  That sound good?  It means updating them will require a code change, but that should be fine.

**Comment by OhMcGoo** [comment] 2020-08-09 18:25
👍🏼

**Closed** 2020-08-11 15:32 UTC
Labels: staging
